# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: Backend/package-lock.json

    - name: Ensure package-lock.json exists
      run: |
        if [ ! -f "package-lock.json" ]; then
          npm install --package-lock-only
        fi
      working-directory: Backend

    - name: Install dependencies
      run: npm ci
      working-directory: Backend

    - name: Start or Restart Backend with PM2
      run: |
          pm2 delete Backend || true
       
          pm2 start app.js --name Backend
       
      working-directory: Backend

